# Generated by Django 3.1.5 on 2021-01-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('MainApp', '0002_auto_20210119_0920'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100, verbose_name='回复内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.diary',
                                            verbose_name='所属日记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'messagetype',
                    models.CharField(choices=[('1', '关注'), ('2', '回复')], max_length=1, verbose_name='消息类型')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs',
                                             to=settings.AUTH_USER_MODEL, verbose_name='消息源')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='OperateApp.reply', verbose_name='所属回复')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                             verbose_name='消息接受者')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', '关注'), ('2', '拉黑')], max_length=1, verbose_name='状态')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                             verbose_name='对象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations',
                                           to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'unique_together': {('user', 'target')},
            },
        ),
    ]
