# Generated by Django 3.1.5 on 2021-01-19 09:20

from django.db import migrations, models

import DjangoUeditor.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='日记内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=14, verbose_name='主题名称')),
                ('themetype', models.CharField(choices=[('0', '公开主题'), ('1', '隐私主题')], default='0', max_length=1,
                                               verbose_name='主题类型')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=7, verbose_name='话题名称')),
                ('describe', models.CharField(max_length=18, verbose_name='话题介绍')),
                ('img', models.ImageField(default='topic/default.png', upload_to='topic/', verbose_name='话题配图')),
                ('info', models.CharField(blank=True, max_length=230, null=True, verbose_name='话题内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('check', models.CharField(choices=[('0', '未通过审核'), ('1', '通过审核')], default='0', max_length=1,
                                           verbose_name='是否通过审核')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
