# Generated by Django 3.1.5 on 2021-01-19 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='diary',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.theme',
                                    verbose_name='所属主题'),
        ),
        migrations.AddField(
            model_name='diary',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='MainApp.topic', verbose_name='所属话题'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('user', 'motif')},
        ),
    ]
